# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import generator_pb2 as generator__pb2


class GeneratorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.generate = channel.unary_unary(
        '/generator.Generator/generate',
        request_serializer=generator__pb2.GenRequest.SerializeToString,
        response_deserializer=generator__pb2.GenReply.FromString,
        )


class GeneratorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def generate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GeneratorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'generate': grpc.unary_unary_rpc_method_handler(
          servicer.generate,
          request_deserializer=generator__pb2.GenRequest.FromString,
          response_serializer=generator__pb2.GenReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'generator.Generator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class ProxyStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.generate = channel.unary_unary(
        '/generator.Proxy/generate',
        request_serializer=generator__pb2.GenRequest.SerializeToString,
        response_deserializer=generator__pb2.GenReply.FromString,
        )


class ProxyServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def generate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProxyServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'generate': grpc.unary_unary_rpc_method_handler(
          servicer.generate,
          request_deserializer=generator__pb2.GenRequest.FromString,
          response_serializer=generator__pb2.GenReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'generator.Proxy', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
